### ISSUE TITLE
?!ban

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#100]
**Hiba leírása**
Amikor kibannolok egy embert, ugyebár meg van oldva, hogy lehessen többet is. Namost. Én bannolok egy embert, "visszaélés" indokkal, és ezért kibannolja azt is, akit úgy hívnak, "visszaélés" - ok nélkül. Esetleg lehetne ?!multiban, mert ez egy eléggé hibás és hülye megoldás.

**Bővebb részletek**
?!ban @MilanTheFortniteGamer Anyád Xanox
"MilanTheFortniteGamer bannolva!"
"Anyád bannolva!"

**Minek kéne történnie?**
lol ezt már leírtam

**Képernyőfotók**
[https://media.discordapp.net/attachments/692430700757909526/726003705060786236/unknown.png?width=379&height=75](url)

**Információk:**
 - OS: Windows 10 Pro 1909 (64bit, 10.0.18363)
 - Discord app verzió: PTB 62314 (713718e)

**Comment by FightMan01** [comment]
fixed:tm:
