### ISSUE TITLE
?!work

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#101]
**Hiba leírása**
Amikor beírom a ?!work-ot, ezt adja ki (képernyőfotó)

**Bővebb részletek**
?!work parancs beírásával idézhető elő

**Minek kéne történnie?**
Működnie kéne :/

**Képernyőfotók**
https://media.discordapp.net/attachments/706931525949718551/727565094380372028/unknown.png?width=492&height=384

**Információk:**
 - OS: Windows 10 Pro 64-Bit 10.0.18363
 - Discord app verzió: Ptb 62522 (5c490db)

**Comment by 182marci** [comment]
röhög a vakbelem

**Comment by 182marci** [comment]
am nem

**Comment by FightMan01** [comment]
Kérlek a hibajelentésekkel ne szórakozz!
