### ISSUE TITLE
Film megosztási lehetőség

### ISSUE THREAD

**Issue by Elydra5** [FightMan01/fightman01bot#102]
Nah hogy is írjam le ezt szépen... Ugye vannak ilyen tirpákok akik dc voicen belül osztanak filmet a többi tirpáknak akik azt megnézik... de ugye ha valaki nitraj nélkül hostol, annak ritka szar a képminőség. Most az lenne itt a csodás ötlet, hogy a botba bele lehetne e tenni egy ilyen filmnézési funkciót, ergo ha valaki beírja, hogy ?!filmnezes (film url-je) akk a bot fogja magát, bekapcsolódik a voiceba aztán ott elkezdi hostolni a filmet. Remélem elég érthetően fogalmaztam meg :ugyvanparasztigazadvan:

**Comment by FightMan01** [comment]
A botok nem tudják azt a végpontot használni.
