### ISSUE TITLE
Template8

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#104]
**Hiba leírása**
Kifelejtettétek az elválasztó hangcsatornákat

**Bővebb részletek**
?!template8 és ?!template8 igen

**Minek kéne történnie?**
elmondtam xd

**Információk:**
még mindig ugyanaz mint régen

**Comment by FightMan01** [comment]
Ez érvénytelen. Egyébként nem felejtettük ki, direkt nem raktuk be, mert rossz szerver konfig esetén bugokat okozhat.
Egyébként az issue template nem véletlen van, az `elmondtam xd` és a `még mindig ugyanaz mint régen` nem oda való. Ezek azért vannak, hogy normálisan kitöltsd.
