### ISSUE TITLE
Welcome image

### ISSUE THREAD

**Issue by Zolkaa** [FightMan01/fightman01bot#105]
**Kérlek írd le az ötlet részleteit.**
Üdvözlő kép. Egy kiválasztott háttérre rászerkeszti a bot a felhasználó nevét és profilképét. (Pillow-val nagyon easy megcsinálni még nekem is sikerült)

**Comment by FightMan01** [comment]
Azért elég kemény vagy, hogy ilyet csinálsz, de nem tudsz egy getguild függvényt normálisan megírni.
Mindenesetre ez nem valószínű a közeljövőben, most több más nagyobb dolog van függőben.
