### ISSUE TITLE
Parancsok összevonása

### ISSUE THREAD

**Issue by klmnblzs** [FightMan01/fightman01bot#108]
Kezd egy kicsit komplikált lenni a sok parancs megjegyzése. Tehetnétek ez ellen, subcommandok egy groupba összehúzásával.
Akár az új **addlogignore**, **removelogignore** parancsot is le tudnátok egyszerűsíteni, az alábbi módon: **?!log [ignore/akármi] [add/remove/akármi]**

:ugyvanparasztigazadvan:

**Comment by Greenoliv** [comment]
Gondolom azért csinálták így, mivel könnyebb egy új parancsot hozzáadni mint nézegetni az argokat. Ettől függetlenül nem rossz ötlet.

**Comment by FightMan01** [comment]
Igen, sokkal egyszerűbb egy új parancs mint egy subcommand/új arg bevezetése.
