### ISSUE TITLE
Még több ötlet

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#11]
?!auto meme/nsfw/koronavirus/euro/  (5/10/ óra vagy naponta automatikusan jönne)
?!bankrablás (Sikeresen kiraboltad a bankot, kaptál 5milliót)
                     (Elkaptak a rendőrök, elvesztetted az összes pénzed )
?!chucknorris
?!roulett
?!russian-roulett
?!channel lock on/off (Channel lezárás/nyitás
?!reddit
?!user-log (Készít 1 meghívó linket a saját szerverhez és kiírja )
?!adminlog Állandó üzenet pl ahol látszik hogy ki mikor lett mutolva 
 (@FightMan01 elküldöm privátba a képet)
Logokat szétszedni ( Pl Channel log,role log,szerver log,stb kép csatolva )

Ha a botnak van valami frissítése akkor kapjunk róla értesítést: 
?!botdmnotify --> Privát üzenetben 
?!botchnotify --> megadott szerveren megadott channelbe

**Comment by FightMan01** [comment]
Oks, a `?!channel lock on/off (Channel lezárás/nyitás` már létezik így: `?!chlock [#csatorna] (@rang > opcionális, amelyik rangot megjelölöd az nem tud írni, default a @everyone)`

A `?!user-log` azt nem teljesen értem. Meghívót elég könnyen lehet készíteni, sztem felesleges ilyen formában. 

Az automatikus meme poszt szerintem majd később lesz.
A többi jónak néz ki, az időmtől függően megvalósítok párat, lehet majd későbbre is csúszik pár.
