### ISSUE TITLE
új economy parancsok

### ISSUE THREAD

**Issue by Barnabas12345-create** [FightMan01/fightman01bot#110]
Lehessen, addolni pénzt, mint az UnbelievaBoat nál, mert ha valami nyereményjáték lenne 1 szerveren és valaki nem ért az UnbelievaBoat-hoz, és pénzt akar kisorsolni, akkor lenne 1 magyar bot ahol van ilyen parancs. Én pl.: értek ahoz a bothoz, de azert ez magyar, meg konnyeb is, és ha lenne ilyen, szerintem nem csak én hanem, mindenki megköszönné!
További szép napot!

**Comment by Barnabas12345-create** [comment]
De csak a nagyobb rangúak tudjanak addolni légyszives.

**Comment by FightMan01** [comment]
Üdv! A pénz rendszer globális, tehát minden szerveren ugyanannyi a pénzed. Ez a pénz premium pontok vásárlására van, mellyel lehet használni a premium parancsokat.
Tehát ilyen lehetőség okkal nincs.
