### ISSUE TITLE
?!kick hiba

### ISSUE THREAD

**Issue by Csarlesz** [FightMan01/fightman01bot#115]
**Hiba leírása**
Nem írja ki hogy Tagok kirúgása jog szükséges, akkor ha alapbol irom a ?!kick parancsot a tobbi argument nélkül 

**Bővebb részletek**
beirod a ?!kick parancsot

**Minek kéne történnie?**
Egyből kiirja azt hogy Hiba! Tagok kirugasa jog szükséges.. Most ugy van hogy member is a missing...

**Képernyőfotók**
Ha lehet, képet csatolj!

**Információk:**
 - android 9
 - google
 - Discord app verzió (nem tudom)

**Comment by TancsicsGergely** [comment]
A report hiányos, szinte semmi használható sincs benne
Amúgy meg ?!initialize és a bot legyen a legmagasabb rangú a szerveren

**Comment by FightMan01** [comment]
Előbb, mint mindig is, az arg check van.
Ez egyébként, ha tudsz bármit is
