### ISSUE TITLE
Muterendszer

### ISSUE THREAD

**Issue by nemtomivagyok** [FightMan01/fightman01bot#118]
**Hiba leírása**
Egy rövid, de jól megfogalmazott leírás a hibáról.
Egy illetőt mutoltunk, utána a bot szövegét töröltük, 2x is lejárt az idő, de nem oldódott fel, maunálisan kellett.
**Bővebb részletek**
Lépések, hogy hogyan tudjuk a hibát előidézni.
?!mute @valaki 10p asd
**Minek kéne történnie?**
Ide írd, hogy szerinted minek kéne történnie.
Az idő leteltével automaitusan unmuteolni
**Képernyőfotók**
Ha lehet, képet csatolj!
Nincs
**Információk:**
 - OS: Android 9
 - Böngésző nem azon
 - Discord app verzió 31.9 legújabb

**Comment by FightMan01** [comment]
Rossz parancsot használsz!
Van erre külön: **?!tempmute**
https://fightman01bot.hu/parancsok
