### ISSUE TITLE
CHLOCK

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#12]
Nem működik a **?!chlock [#csatorna]** parancs

**Comment by FightMan01** [comment]
Ír valami hibát?
Nem lehet, hogy a szervereden a rangok úgy vannak bekonfigolva, hogy ne menjen?
A hiba biztos a botban van?

**Comment by FightMan01** [comment]
Ja és kérlek az előre megadott template-ek alapján csinálj ilyen bejelentést.
