### ISSUE TITLE
Hiba 

### ISSUE THREAD

**Issue by Jundkilleryt12** [FightMan01/fightman01bot#120]
**Hiba leírása**
Egy rövid, de jól megfogalmazott leírás a hibáról.
A rolebannal mindenkit lehet egyszerre bannolni
**Bővebb részletek**
Lépések, hogy hogyan tudjuk a hibát előidézni.
/roleban @everyone
**Minek kéne történnie?**
Ide írd, hogy szerinted minek kéne történnie.
Annak hogy a bot azt írná hogy: Everyonet nem bannolhatom!
**Képernyőfotók**
Ha lehet, képet csatolj!

**Információk:**
 - OS: [pl.: MacOS 10.15.4]
 - Böngésző (ha arról használod a discordot) [pl.: safari]
 - Discord app verzió (ha azt használod) [pl.: Canary 57889 (492e1b6)]

**Comment by 182marci** [comment]
Ez a hiba már réges régen javítva lett.
