### ISSUE TITLE
nem működik a ?!tempmute parancs

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#122]
**Hiba leírása**
Nem működik a tempmute parancs

**Bővebb részletek**
?!tempmute @említés 10s asd

**Minek kéne történnie?**
xD, működnie

**Képernyőfotók**
-

**Információk:**
Nem szükséges

**Comment by TancsicsGergely** [comment]
Ez nem megfelelő leírás, kérlek javítsd, és ha kész, szólj nekünk.
