### ISSUE TITLE
Bejelentés csatorna készítés

### ISSUE THREAD

**Issue by Elydra5** [FightMan01/fightman01bot#126]
NA nibbák mivel ugye van olyan lehetőség, hogy ?!setnsfw adott csatorna, akkor kéne egy olyan is, hogy ?!setbejelentés adott csatorna, és akk bejelentő csatornává tenné az adott csatornát. :200iq:

**Comment by FightMan01** [comment]
Sajnos ezt jelenleg a botok nem tudják elintézni :c
