### ISSUE TITLE
Hangcsatornába való belépés HIBA

### ISSUE THREAD

**Issue by daviidkaa** [FightMan01/fightman01bot#127]
**Hiba leírása**
Ha el akarok indítani egy zenét a bot rákeres a zenére de később kiírja hogy a hangcsatornába való csatlakozás sikertelen. És Rádiót, semmi sem megy.

**Bővebb részletek**
1. Beírjuk hogy ?!play (cím) vagy valamien hangcsatornás parancsot.
2. Kiírja a bot hogy Nem tudott csatlakozni.

**Minek kéne történnie?**
Belépnie és zenét vagy rádiót raknia.

**Képernyőfotók**
Csatolok.

![Screenshot_20200805-191049_Discord](https://user-images.githubusercontent.com/65349338/89442749-9fb44080-d74f-11ea-9076-f9335fd1bd22.jpg)

**Információk:**
 - Discord app verzió 33.8 
Android telefon

**Comment by TancsicsGergely** [comment]
Heló
Erről a hibáról már tudunk, javítjuk amint tudjuk.
További infókért figyeld a dev szerverünket vagy ezt az oldalt: https://status.fightman01bot.hu/incident/20533

**Comment by FightMan01** [comment]
Javítva az új discord.py frissítésben.
