### ISSUE TITLE
Néhány probléma

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#13]
**Hiba leírása**
Lassú a bot
Nem jelzi, ha nem tudja odaadni a muted rangot a megemlített tagnak

**Bővebb részletek**
Képeket csatolok

**Minek kéne történnie?**
Esetleg kiírhatná, ha nem tudja odaadni a rangot a tagnak

**Képernyőfotók**
https://cdn.discordapp.com/attachments/699605050477248555/699908808956313640/unknown.png
https://cdn.discordapp.com/attachments/699605050477248555/699908856469520384/unknown.png
https://cdn.discordapp.com/attachments/699605050477248555/699909129237692466/unknown.png

**Információk:**
 - OS: Windows 10 Pro 1909 (Windows 10 64-Bit [10.0.18363])
 - Böngésző: nem azt használom, de amúgy Google Chrome és Opera GX (ha csak onnan tudom)
 - Discord app verzió: Stable 58164 (aa9f89f)

**Comment by FightMan01** [comment]
1. A bot nem lassú, max az olyan parancsoknál, ahol van lekérés.
2. Ez helytelen használata a parancsnak, ahogyan azt le is írja.
<img width="204" alt="image" src="https://user-images.githubusercontent.com/29693718/79320694-7fdfdf00-7f0a-11ea-8aa3-af5fee4d06f9.png">

**Comment by FightMan01** [comment]
Nem `5min`, hanem `5m`

**Comment by iamdoms** [comment]
Nem is én írtam azokat.

**Comment by FightMan01** [comment]
Akkor nem értem a gondot.

**Comment by iamdoms** [comment]
Valakit le akartam muteolni. Nem sikerült. Aztán ő akart kickelni, de nem volt joga. Én néhányszor muteoltam és vagy nem sikerült, vagy sikerült, de mégsem. És lassú volt a bot.

**Comment by FightMan01** [comment]
Azért lehetett akkor lassú, mert a jogokat próbálhatta minden csatihoz beállítani. Valszeg nem sikerül neki, vagy ha sikerült is, töröltétek a Muted rangot, vagy pedig egy másik rang a muted rangot írja felül.
