### ISSUE TITLE
Bugos a weboldal

### ISSUE THREAD

**Issue by F1RST11** [FightMan01/fightman01bot#131]
**Információk:**
 - OS: 10.10.5
 - Böngésző: safari
 
![Képernyőfotó 2020-08-14 - 12 44 45](https://user-images.githubusercontent.com/68382177/90236922-1924f080-de2c-11ea-82b7-f50fe0b7fd49.png)

**Comment by klmnblzs** [comment]
Bruh. Körülbelül 10x mondtuk el, hogy a dashboard felújításon esik át, addig a régit nem lehet használni.
