### ISSUE TITLE
[ISMERT HIBA] A bot válaszideje jelentősen megnő 21:00 után

### ISSUE THREAD

**Issue by FightMan01** [FightMan01/fightman01bot#134]
**Hiba leírása**
A bot válaszideje jelentősen megnő 21:00 után, néha többször is újraindul.

**Bővebb részletek**
A hiba újraindítás után megszűnik, ám az adatbázis gyakran beakad.

**Megjegyzés**
A hiba okát vizsgáljuk. DDoS támadások kizárva, ugyanis minden más szolgáltatás tökéletesen működik! Szíves türelmeteket kérjük ezidő alatt és köszönjük a megértéseket!

**Információk:**
 - OS: MacOS 10.15.6
 - Discord app verzió (ha azt használod): Canary 65438 (f1669cb)

**Comment by B1gLev** [comment]
Hogy akad be egy adatbázis? Nem ment vagy micsoda?

**Comment by FightMan01** [comment]
Úgy néz ki, hogy ez a hiba megoldódott időközben.
