### ISSUE TITLE
A zene és a rádió lejátszása közben folyamatos az akadozás

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01/fightman01bot#135]
**Hiba leírása**
Egy rövid, de jól megfogalmazott leírás a hibáról.

**Bővebb részletek**
Lépések, hogy hogyan tudjuk a hibát előidézni.

**Minek kéne történnie?**
Ide írd, hogy szerinted minek kéne történnie.

**Képernyőfotók**
Ha lehet, képet csatolj!

**Információk:**
 - OS: [pl.: MacOS 10.15.4]
 - Böngésző (ha arról használod a discordot) [pl.: safari]
 - Discord app verzió (ha azt használod) [pl.: Canary 57889 (492e1b6)]

**Comment by FightMan01** [comment]
Ez elég kevés infó, a problémát én nem tudom előidézni jelen pillanatban. 
Ellenőrizd az internet kapcsolatodat. Lent láthatod a pingedet is, nem jó ha túl sok.

**Comment by zarandthebende** [comment]
Köszi, megpróbálom mégegyszer, lehet hogy az internettel van a baj Feladó: Németh ÁronElküldve: 2020. augusztus 19., szerda 19:18Címzett: FightMan01/fightman01botMásolatot kap: zarandthebende; AuthorTárgy: Re: [FightMan01/fightman01bot] A zene és a rádió lejátszása közben folyamatos az akadozás (#135) Ez elég kevés infó, a problémát én nem tudom előidézni jelen pillanatban.Ellenőrizd az internet kapcsolatodat. Lent láthatod a pingedet is, nem jó ha túl sok.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
