### ISSUE TITLE
?!játékinformáció

### ISSUE THREAD

**Issue by Greenoliv** [FightMan01/fightman01bot#136]
**Kérlek írd le az ötlet részleteit.**
Írjon egy leírást is a játékról.

Pl. Minecraft:

A Minecraft egy sandbox építkezős játék, amit a Mojang AB alapítója, Markus Persson készített. A játékmenet során a játékosok kapcsolatba lépnek a játék világával különböző típusú blokkok lehelyezésével és széttörésével egy háromdimenziós környezetben. Ebben a környezetben a játékosok kreatívan építhetnek építményeket, művészi alkotásokat több és egyjátékos szervereken.

**Comment by klmnblzs** [comment]
A "?!játékinformáció" parancs tudtommal a játékokhoz szükséges igényt írja le, nem pedig bemutatót. Eléggé fájdalmas lenne egyesével API nélkül szövegeket írogatni random játékokhoz.

**Comment by Greenoliv** [comment]
?!játék**információ**

**Comment by klmnblzs** [comment]
A gépigény is egy **információ**

**Comment by FightMan01** [comment]
Lesz gépigény alias.
