### ISSUE TITLE
Autorole BUG

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01/fightman01bot#138]
**Hiba leírása**
Az autorole funkció nem működik rendesen

**Bővebb részletek**
"?!autorole on" beírása, és a rang kiválasztása után a bot azt írja, hogy "funkció sikeresen kikapcsolva" (nem egyértelmű, hogy mi történt

**Minek kéne történnie?**
A bot bekapcsolja a funkciót, és kiírja hogy mi történt

**Képernyőfotók**
Ha lehet, képet csatolj!

**Információk:**
 - OS: [Microsoft Windows 10 Pro]

**Comment by FightMan01** [comment]
Az autorole parancs interaktív.
