### ISSUE TITLE
Log-al kapcsolatban

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01/fightman01bot#139]
**Kérdés leírása**
Kéne segítség a Loghoz, mert sehogy nem tudom újra bekapcsolni. A bot kiírja, hogy már be van kapcsolva, de megse, mert nem logol. A Logmodes-nél ki van váladztva, hogy mindent logoljon, de mégse teszi. Ugyanez a Voice lognál is :(

**Comment by Zolkaa** [comment]
Esetleg nem csináltad újra a log csatornát? Mert az okozhatja ezt a problémát

**Comment by zarandthebende** [comment]
De...és hogy oldjam meg?
