### ISSUE TITLE
?!névnap (hh.nn)

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#140]
Lehetne névnap parancs egy megadott hónaphoz és naphoz. Pl `?!névnap (hh.nn)`
Pl. Ha az enyém akarja valaki lekérni, `?!névnap 08.04`, és kiírja, hogy ekkor Dominik/Domonkos/Dominika névnap volt.
Meg lehet oldani?
(https://fightman01bot.hu/parancsok alapján írva, tehát [ ] = kell, ( ) = opcionális)

**Comment by FightMan01** [comment]
aztakurvamindenitvalakirájötthogymiafasznakvankétkülönzárójel:o
