### ISSUE TITLE
Koronavírus parancs fejlesztése

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01/fightman01bot#141]
**Itt vannak az ötlet részletei :D **
Az lenne az ötlet, hogy külföldi országokból is le lehessen kérdezni a koronavírus-adatokat (?!koronavírus [pl. kína] )
**Ennyi.**

**Comment by FightMan01** [comment]
Szerintem ez egyelőre felesleges, az emberek 98%-a a magyar adatokra kíváncsi.
