### ISSUE TITLE
Full shop purge

### ISSUE THREAD

**Issue by TancsicsGergely** [FightMan01/fightman01bot#145]
Kéne egy szerver alapú full shop purge. Már többször találkoztam olyannal, hogy valaki megemlít egy rangot mint item név, majd később törli azt a rangot. A ?!delete_item @deleted-role nem oldja meg, főleg, hogy több ilyen is van egy szerveren belül...

**Comment by klmnblzs** [comment]
Köszönjük szépen, Táncsics Gergely úr.
