### ISSUE TITLE
egy kérdés

### ISSUE THREAD

**Issue by Bence-3878** [FightMan01/fightman01bot#15]
Ellenőrzési csatornát hogy tudok csinálni? A honlapon nem találtam a megfelelő parancsot ,mezét az admin parancsokat külön kéne szedni.

**Comment by Bence-3878** [comment]
> Ellenőrzési csatornát hogy tudok csinálni? A honlapon nem találtam a megfelelő parancsot ,mezét az admin parancsokat külön kéne szedni.

**Comment by FightMan01** [comment]
Üdv! Ezt a csatornát a `?!setup` paranccsal tudod beállítani.

**Comment by Bence-3878** [comment]
köszi
