### ISSUE TITLE
Szerver mentés hiba

### ISSUE THREAD

**Issue by laciberecz3** [FightMan01/fightman01bot#158]
**Hiba leírása**
A szerver mentés parancsnál észleltem egy két hibát!

**Bővebb részletek**
Használtam a szerver mentés parancsot! Utána pedig a mentesload parancsot szerettem volna használni! Amikor beírtam akkor a bot privátban értesített hogy a folyamat elkezdődött! DE Eltelt 10 perc és meg nem történt szinte semmi sem a szerverrel! Ez volt az eggyik hiba. A másik az pedig az lenne hogy, a rangokat azokat legenerálta csak visszafelé! Szóval a tulaj tang van legalul és a bot rangok pedig fent. 

**Minek kéne történnie?**
Szerintem le kéne generálnia a szerver amit elmentett! 

**Képernyőfotók**
Ha lehet, képet csatolj! Telefonról nem tudtam képet küldeni de discordon ha kell akkor tudok küldeni. 

**Információk:**
 - OS: xiaomi mi 8 lite telefon, és MIUI 11.0.3.|| Android verzió: 10
 - Discord app verzió: fogalmam sincs

**Comment by laciberecz3** [comment]
Ja és nem vonta le a prémium pontomat. Ha egyáltalán le kellett volna vonnia :D

**Comment by TancsicsGergely** [comment]
A mentés funkció még béta, tudjuk, hogy vannak vele hibák
A pp-t meg direkt nem vonja le, most minden ingyenes.

**Comment by FightMan01** [comment]
Egyébként, a bot rangja legyen legfelül.

**Comment by laciberecz3** [comment]
Hát igen. De a többi rang ami máshol sorrendbe volt akkor az itt is sorrendbe legyen. És köszönöm a választ!

**Comment by klmnblzs** [comment]
?!initialize parancsot ilyen esetben ajánlom, mivel nem minden esetbe fogja kiírni a bot a hibát
