### ISSUE TITLE
Mute hiba

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01/fightman01bot#159]
**Hiba leírása**
?!mute @említés esetén nem történik semmi

**Bővebb részletek**
Muteolás esetén nem történik semmi, tempmutenél szintén

**Minek kéne történnie?**
Muteolódnia kéne az illetőnek

**Képernyőfotók**
Nem szükséges szerintem

**Információk:**
 - OS: [Microsoft Windows 10 Pro 64bit
 - Discord app verzió (ha azt használod) [pl.: Canary 66346 (e5c35d3)

**Comment by FightMan01** [comment]
Kérlek írd be a ?!initialize parancsot, valószínűleg a botnak nincs joga.

**Comment by zarandthebende** [comment]
Ok, megpróbálom

**Comment by FightMan01** [comment]
Esetleg megpróbálhatnád a bot rangját feljebb húzni, vagy ellenőrizni, hogy nincs-e letiltva a parancs.

**Comment by zarandthebende** [comment]
Bot van legfelül, nincs letiltva parancs

**Comment by FightMan01** [comment]
Pedig nálam tökéletesen teszi a dolgát.
<img width="802" alt="image" src="https://user-images.githubusercontent.com/29693718/92147107-ee223100-ee1a-11ea-8bdc-9e8a11bbf149.png">

**Comment by zarandthebende** [comment]
Működik mostmár, muteot elfelejtettem felhúzni😅
**Köszi a segítséget**
