### ISSUE TITLE
?!setytannounce paranccsal kapcsolatos hiba

### ISSUE THREAD

**Issue by xpvadasz** [FightMan01/fightman01bot#16]
**Hiba leírása**
Nem válaszol a linkre a ?!setytannounce parancsnál.

**Bővebb részletek**
Ha jó linket küldök akkor nem válaszol semmit és nem is állítja be magát.(kipróbáltuk)

**Minek kéne történnie?**
Esetleg valamit írni,de minimum értesíteni ha jön videó.

**Képernyőfotók**
![Képernyőfelvétel (56)](https://user-images.githubusercontent.com/63862138/79580873-efe89380-80c9-11ea-858c-4de6bf2d85c3.png)

**Információk:**
 - Windows 10 Pro
 - Discord app verzió

**Comment by FightMan01** [comment]
Helo! Ahogy program is írta: van fent videó?
Mert a bot úgy ellenőriz, hogy megnézi talál-e videót.

**Comment by xpvadasz** [comment]
Oda írtam hogy kipróbáltuk. Raktam fel eggyet, de 20 perc múlva sem jött semmi.

**Comment by xpvadasz** [comment]
Amúgy van fent állandóan egy pár

**Comment by FightMan01** [comment]
De utánna állítsd be, miután már van fent videó, mert ahogy írtam: `Mert a bot úgy ellenőriz, hogy megnézi talál-e videót.` - Így nézi a csatorna érvényességét.

**Comment by FightMan01** [comment]
És amúgy ma megpróbáltad?

**Comment by xpvadasz** [comment]
Én azt próbáltam ki, hogy ha felrakok egyet +ba a 17 mellé akkor küld-e értesítést.

**Comment by FightMan01** [comment]
Most néztem meg:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/29693718/79581564-dc89f800-80ca-11ea-9fa1-0f43f124d442.png">

**Comment by FightMan01** [comment]
De amint a képen is láthatod a beállítás így megy végig.

**Comment by xpvadasz** [comment]
most se jó nálam

**Comment by FightMan01** [comment]
Küldj privibe meghívót

**Comment by xpvadasz** [comment]
Átnézem a rangjait
rendben.

**Comment by FightMan01** [comment]
Sőt, most látom:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/Fightman01Bot/fightman01 debug/yt_announcer.py", line 214, in setytannounce
    if await letezik(str(ctx.guild.id), str(channel_id)):
  File "/home/Fightman01Bot/fightman01 debug/yt_announcer.py", line 57, in letezik
    for x in data[sid]["channels"]:
KeyError: '519750245186273300'
```

Magyarul, te nem a `be` lehetőséget használtad.

**Comment by xpvadasz** [comment]
Az volt a gond, azt hittem először hozzá kell adni mint egy másik botnál.

**Comment by FightMan01** [comment]
Ez a bot logikus alapokra épül :)
