### ISSUE TITLE
?!reminder parancs hiba

### ISSUE THREAD

**Issue by petipeti156** [FightMan01/fightman01bot#163]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALKAMELYIK FELESLEGES!!!***

**Hiba leírása**
A reminder parancsnál lehet mínusz számot megadni 

**Bővebb részletek**
-

**Minek kéne történnie?**
Ki kéne írja azt, hogy nem lehet mínusz szám. 

**Képernyőfotók**
![Screenshot_20200905_172053](https://user-images.githubusercontent.com/61799060/92308287-ec807680-ef9c-11ea-8184-1ef405e59ef2.jpg)

**Információk:**
 - OS: Android 10
 - Böngésző (ha arról használod a discordot) [pl.: safari] - 
 - Discord app verzió (ha azt használod) [pl.: Canary 57889 (492e1b6)] -

**Comment by Elydra5** [comment]
Hallod már megeloztelek xddd nézz be dev szerora

**Comment by petipeti156** [comment]
nemá xdd

**Comment by Elydra5** [comment]
![ED308A82-4465-4F4F-8E63-6AAAD1E3B136](https://user-images.githubusercontent.com/66174724/92308364-513bd100-ef9d-11ea-8e55-a5a220043b0d.png)
Xd

**Comment by klmnblzs** [comment]
![image](https://user-images.githubusercontent.com/40501930/92308414-a677e280-ef9d-11ea-9f89-ef98ada9fce4.png)
