### ISSUE TITLE
Alias kiírása szintaktika hibánál.

### ISSUE THREAD

**Issue by Greenoliv** [FightMan01/fightman01bot#164]
**Kérlek írd le az ötlet részleteit.**
Példa. 

Van egy ?!alma @ping parancs aminek az aliasa a ?!körte @ping. 

Ha beírom hibásan hogy ?!körte (ping nélkül) akkor azt írja ki hogy Helyes használat... ?!körte @ping és ne azt hogy ?!alma @ping

**Comment by FightMan01** [comment]
Értem, viszont direkt az alap parancsot írja ki. Ez főleg azért is, mivel a weboldalon így található meg, mások, akik ezt látják és ki akarják keresni, megtalálják.
