### ISSUE TITLE
3 ötlet

### ISSUE THREAD

**Issue by adamgamerpro12** [FightMan01/fightman01bot#165]
**Kérlek írd le az ötlet részleteit.**
Egy bő, jól érthető leírás az ötletedhez!
Szülinap értesítő
Tiktok videó értesítő rendszer
Fordító kehetőség

**Comment by zarandthebende** [comment]
A szülinap értesítőnek nem látom értelmét...a többi az egész jó

**Comment by FightMan01** [comment]
A tiktok-os nem lesz, mert az egy szégyen.
A szülinap értesítő részben készül.
A fordító volt, de sajnos a google api nem enged olyan sok lekérést :(
