### ISSUE TITLE
Member+ funkció

### ISSUE THREAD

**Issue by Elydra5** [FightMan01/fightman01bot#166]
Nyaszóval drága uraim ugye van a member+ bot, ami olyan alapon működik, hogy be kell lépned egy szerverre, kapsz pontot minden belépésért, és így tudsz hirdetést venni, és a te szervered tudod hirdetni vele, ahova így belépnek emberek, mert kapnak érte pontokat. (remélem eddig érthetően fogalmaztam). lehetne egy ilyen funkció az fm01ben is, ami mondjuk prémium pontokkal üzemelne. pl ?!buyad 3 <szöveg> és akk 3 levonna 3 pontot, és 3 invite után leszedné a hirdetőfalról az adott szerver linket. meg pl boostot is lehetne venni, és ha valaki boostolja a szervert mert ki volt téve hirdetésbe, akkor ilyen ?!boosts claim alapon be tudná gyűjteni a pp-ket érte (mondjuk 100pp-t)
ha voteol a dc.gg-n vagy hol akk meg kap +2 pp-t és kész.
na kb ennyi lenne, remélem megcsináljátok mer köll a tag verte meg

**Comment by FightMan01** [comment]
little confusion

**Comment by TancsicsGergely** [comment]
hát
részben értem
részben viszont confusion

**Comment by FightMan01** [comment]
Hosszas gondolkodás és a bot tanulmányozása után nem hiszem, hogy csinálok ilyet. Ez egy olyan dolog, ami külön botot igényelne.
