### ISSUE TITLE
?!poll

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#169]
**Hiba leírása**
Hiba 1: a hibajelentés templatejénél azt írtátok, hogy VALKAMELYIK
Hiba 2: a `?!poll` parancsnál csak egy szögletes zárójelet ír ki ha nincs megadva egy argument

**Bővebb részletek**
?!poll-t beírod argumentek nélkül, és ott az error message

**Minek kéne történnie?**
Egy error message:
"Helyes használat: ?!szavazás [szavazás szövege]

**Képernyőfotók**
https://media.discordapp.net/attachments/692430721981349948/757255832844107866/unknown.png?width=226&height=154

**Információk:**
 - OS: Win 10 Home 1809
 - Discord app verzió: Canary 67442 (f3d7b2b)

**Comment by FightMan01** [comment]
bruh
