### ISSUE TITLE
Kréta rendszer értesítő hiba

### ISSUE THREAD

**Issue by Adam1236126** [FightMan01/fightman01bot#173]
**Hiba leírása**
Napi szinten küld egy olyan üzenetet hogy: "Kréta rendszer értesítő : Új számonkérés:  : 
"

**Képernyőfotók**
![hiba](https://user-images.githubusercontent.com/66472233/94263972-30c8bc00-ff36-11ea-9934-8d026d5cc696.PNG)
![hiba2](https://user-images.githubusercontent.com/66472233/94263977-31f9e900-ff36-11ea-87dc-623bd3e8fad4.PNG)
![hiba3](https://user-images.githubusercontent.com/66472233/94263979-32927f80-ff36-11ea-8d9b-145e4c1a3e29.PNG)

**Comment by FightMan01** [comment]
A javításra kísérletet tettünk.
https://discord.gg/dDhyRNP
