### ISSUE TITLE
A Weboldalt Valamiért Nem Biztonságos

### ISSUE THREAD

**Issue by Momi0123** [FightMan01/fightman01bot#174]
Azt Történt, Amikor néztem akkor mutatta hogy
a Weboldal Nem biztonságos,
Képet is tudok küldeni rajta.
![Képernyőfelvétel (292)](https://user-images.githubusercontent.com/71933376/94342419-3c3ce580-0011-11eb-8272-bc147190e8d6.png)
Itt van.

**Comment by TancsicsGergely** [comment]
Köszi, majd ránézek.

**Comment by Momi0123** [comment]
köszike.

**Comment by FightMan01** [comment]
Azért ismeri fel annak, mert a domain 5 hónapos. És ezek a szarok szerint ez túl új, potencionálisan veszélyes

**Comment by Momi0123** [comment]
ja és van mégegy

**Comment by Momi0123** [comment]
![Képernyőfelvétel (293)](https://user-images.githubusercontent.com/71933376/94342649-b1f58100-0012-11eb-9e9e-9650822d8dce.png)

**Comment by FightMan01** [comment]
Igen, vannak hirdetések a weboldalon.

**Comment by Momi0123** [comment]
hát ja sajna

**Comment by TancsicsGergely** [comment]
Mindkettő a Google cucca

**Comment by Momi0123** [comment]
jaja

**Comment by Momi0123** [comment]
azok

**Comment by Momi0123** [comment]
na de azért ne itt csevegéjünk
