### ISSUE TITLE
?!setytannounce nem fogadja el a linket

### ISSUE THREAD

**Issue by kBalix** [FightMan01/fightman01bot#175]
**Hiba leírása**
Ha beírom, hogy setytannounce, on, egy csatorna link (több csatornával is próbáltam) azt írja, hogy helytelen linket adtam meg.

**Minek kéne történnie?**
El kéne fogadnia a linket, és folytatni a beállításokat

**Képernyőfotók**
![Screenshot_20200928_203554_com discord](https://user-images.githubusercontent.com/59265474/94472311-da27e000-01ca-11eb-9825-3efb79193ae3.jpg)

**Információk:**
 - OS: Windows 10, android 10
 - Böngésző: Chrome, edge

**Comment by FightMan01** [comment]
Régóta nem megy, ismert probléma, dev szerveren írtunk róla elég sokat....

**Comment by kBalix** [comment]
Ja ok, nem figyeltem
