### ISSUE TITLE
Koronavirus

### ISSUE THREAD

**Issue by szkobzi** [FightMan01/fightman01bot#176]
Napi koronavírus parancs. 
Ami a névnaphoz hasonlóan működne. 

Parancs:?!koronaset #xyy 10:00 (Ekkor küldené el, általában mindig ilyenkor jönnek az adatok.) 

Elore is köszi

**Comment by FightMan01** [comment]
Sajnos annyira kiszámíthatatlan, hogy mikor teszik közzé (néztem minden nap), hogy ezt nem merem most bevállalni. (lehet, hogy 10:10-kor teszik közzé, de a bot emiatt az előző napit küldte el)
