### ISSUE TITLE
Most komoly? Rossz a ?!mentesload és elvette a jogaimat

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#179]
**Hiba leírása**
Beírtam hogy ?!mentesload egy 50+ tagos szerveren, erre törölte az összes csatornát, és most nincs jogom létrehozni újat.

**Bővebb részletek**
sztem csak velem történt meg

**Minek kéne történnie?**
egyértelmű

**Képernyőfotók**
https://imgur.com/a/oy7pjc0

**Információk:**
 - OS: Win10 home 1809
 - Böngésző: Kugli Chrome

**Comment by FightMan01** [comment]
DEV szerver, egyébként a legújabb frissítésben a mentés rendszer teljesen újra lett írva, teljesen újra lett gondolva.
