### ISSUE TITLE
Eval-t a statusban jelzi.

### ISSUE THREAD

**Issue by 2005zsombor2005** [FightMan01/fightman01bot#18]
**Hiba leírása**
A bot a statusban jelzi az eval parancsot, de ahoz nekünk nincs jogunk használni.

**Minek kéne történnie?**
Nem kéne jeleznie a statusban.

**Információk:**
 -2005zsombor2005#0061 voltam. :)

**Comment by FightMan01** [comment]
Itt az összes parancs közül sorsol, ez nem nagy hiba.
