### ISSUE TITLE
Szerver készítő template probléma

### ISSUE THREAD

**Issue by varso01** [FightMan01/fightman01bot#180]
![image](https://user-images.githubusercontent.com/53610770/96609045-5f01a780-12fa-11eb-976c-2df70726c788.png)

A ?!template9 igen parancs kiadására a bot semmit sem csinál.

**Comment by FightMan01** [comment]
hm

**Comment by FightMan01** [comment]
DM-ben sem kaptál semmit?

**Comment by FightMan01** [comment]
Mert a csatiba nem ír, csak DM-be ilyenkor

**Comment by varso01** [comment]
Privátban sem jött semmi.

**Comment by FightMan01** [comment]
Most teszteltem, nekem működik. Ellenőrizd, hogy tudsz-e DM-ben fogadni a bottól üzenetet.

**Comment by varso01** [comment]
?!help parancs eredménye eljött privátban, utána már a template parancs is működött, köszi a helpet! ;)

**Comment by FightMan01** [comment]
Pedig nekem sikerült. Esetleg azt nézd még meg, hogy a bot rangja a legmagasabb-e a szerveren.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/29693718/96609832-3c23c300-12fb-11eb-9cf8-7d7c611235a2.png">

**Comment by FightMan01** [comment]
Ja, közben láttam, hogy sikerült, csak discordon nem írta ki végig :D
