### ISSUE TITLE
Case-sensitive parancskereső a weboldalon

### ISSUE THREAD

**Issue by petipeti156** [FightMan01/fightman01bot#182]
A parancskeresőnél csak kisbetűs parancsokra mutat keresési eredményt, ez szerintem lehetne case-sensitive.
![image](https://user-images.githubusercontent.com/61799060/97038363-fd943f80-156a-11eb-8b7d-6f924facdd45.png)
![image](https://user-images.githubusercontent.com/61799060/97038373-fff69980-156a-11eb-9863-11d2cfaedbdd.png)

**Comment by FightMan01** [comment]
Amire te gondolsz, az a case-insensitive :D
De amúgy jó ötlet.

**Comment by petipeti156** [comment]
> Amire te gondolsz, az a case-insensitive :D
> De amúgy jó ötlet.
ja igen, keverem a kettőt D:

**Comment by FightMan01** [comment]
Egyébként megvalósítva.
