### ISSUE TITLE
Hitelesítő Rendszerhez: Ha ki van kapcsolva a felhasználónak a Privát Üzenetek Fogadása

### ISSUE THREAD

**Issue by kispintyi** [FightMan01/fightman01bot#184]
**Ha ki van kapcsolva a Privát Üzenetek Fogadása a felhasználó számára, akkor erről értesítse őt a megadott hitelesítő szobában, hogy engedélyezze a beállításokban (pontos instrukciókat is megadhat hozzá) és hogy ezután lépjen ki a szerverről és vissza, ez az üzenet kb 1-2 perc után eltűnne, sztem így nem zavarna senkit sem :) De nem tudom hogy ti ezt hogy látjátok... Majd eldől :D :)**

**Comment by FightMan01** [comment]
Egyelőre szerintem elég, ha a szerver tulaját értesíti, mert ő tudja manuálisan is hitelesíteni ;)
