### ISSUE TITLE
?!ph parancs szerintem nem megfelelően működik

### ISSUE THREAD

**Issue by xpvadasz** [FightMan01/fightman01bot#19]
**Hiba leírása**
Csak azt a választ adja a bot, hogy kérlek várj...

**Bővebb részletek**
Beírom úgy a parancsot ahogy kell,de nem történik semmi a fent említett dolgon kívül.

**Minek kéne történnie?**
Nem tudom, mert ezt nem szerete volna leírni a weboldal készítője :D 

**Képernyőfotók**
![#spamisztika - Discord 2020  04  21  13_32_02](https://user-images.githubusercontent.com/63862138/79861337-8bcd1480-83d4-11ea-914e-343320a330f7.png)

**Információk:**
 - OS: Windows 10 Pro
 - Discord Stable 58583

**Comment by FightMan01** [comment]
Ez API alapú, ezzel sajnos én nem tudok mit csinálni jelenleg.

**Comment by xpvadasz** [comment]
Rendben, nem fontos dolog csak jeleztem.
