### ISSUE TITLE
fight man bug

### ISSUE THREAD

**Issue by Godrogi** [FightMan01/fightman01bot#191]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
a fightman01 bot nál észletem egy rádó val kapcsolatos hibát.

**Bővebb részletek**
bemész egy csatornába és aktiválod a rádió üzemmódot és léptesd ki a robotot

**Minek kéne történnie?**
hiba történt kérlek próbáld a ?!confix parcsot majd próbáld urja.

képernyő fótó
![image](https://user-images.githubusercontent.com/73785679/97805608-6bb9c000-1c57-11eb-89ca-5423934c1a68.png)

**Információk:**
 -windos 10
 - discord alkalmazás
 - legfrisseb
![minden](https://user-images.githubusercontent.com/73785679/97805643-b20f1f00-1c57-11eb-84d6-c29dc61387b4.png)

**Comment by FightMan01** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/29693718/97808179-b5a9a280-1c65-11eb-9f36-dae70cef15db.png">
