### ISSUE TITLE
az ?!initalize meghalt

### ISSUE THREAD

**Issue by Godrogi** [FightMan01/fightman01bot#193]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
?!initalize parancs nem válaszol

**Bővebb részletek**
beirod chatre ?!initalize

**Minek kéne történnie?**
elindul az ellenörzés

**Képernyőfotók**
![image](https://user-images.githubusercontent.com/73785679/97805964-87be6100-1c59-11eb-921f-b43aa6311720.png)

**Információk:**
 - windos 10
 dicord legfrisseb

**Comment by FightMan01** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/29693718/97808211-edb0e580-1c65-11eb-9de0-2f9f4d065558.png">
