### ISSUE TITLE
Paraancsok

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#2]
-?!reportset #channel
-?!report szöveg (Bárki tudjon jelenteni, és a bot elküldi az előbb megadott channelbe  ) Képet is lehessen küldeni !

-Reaction role minden welcome üzenetnél 

-A parancsokat le lehessen korlátozni ki használja 

-?!timemultipoll

**Comment by FightMan01** [comment]
Okés, felírom ;)

**Comment by FightMan01** [comment]
Illetve még erre, hogy `Reaction role minden welcome üzenetnél`

Ezt simán megoldod a `?!rangsetup` paranccsal is.

**Comment by iamdoms** [comment]
?!report-nál nem lehetne megoldani a képeket szerintem, max. link formájában (media.discordapp)

**Comment by FightMan01** [comment]
> ?!report-nál nem lehetne megoldani a képeket szerintem, max. link formájában (media.discordapp)

Meg lehet, addig, amíg a felhasználó a képet nem törli.

**Comment by iamdoms** [comment]
> > ?!report-nál nem lehetne megoldani a képeket szerintem, max. link formájában (media.discordapp)
> 
> Meg lehet, addig, amíg a felhasználó a képet nem törli.

oh

**Comment by Roli0109** [comment]
@FightMan01  remélem minél hamarabb

**Comment by FightMan01** [comment]
#5
