### ISSUE TITLE
óra hibba nyeremény játék oldalon

### ISSUE THREAD

**Issue by Godrogi** [FightMan01/fightman01bot#200]
***Ezek a pontok azért vannak, hogy a mi munkánkat is segítsek! NINCS OLYAN, HOGY VALAMELYIK FELESLEGES!!!***

**Hiba leírása**
a bot órája nincs vissza állitva
**Bővebb részletek**
?!role
**Minek kéne történnie?**
?!rolegiveaway [@rang] [idő (végére az egység jele)] [nyertesek száma] [szöveg]
![image](https://user-images.githubusercontent.com/73785679/98142581-4384c800-1ec8-11eb-9d3f-84ec24ab34dc.png)

**Információk:**
 win 10
dc legfriisbed 
APp!

**Comment by Godrogi** [comment]
Nem hiba
Kösznöm a megértést de az oldal rosszul mutatja

**Comment by FightMan01** [comment]
A bot órája a discord órájával szinkronizálódik. A weboldalra integrált órát külön állítjuk, az az egyetlen, ami mindentől független. Köszönjük az észrevételt.
