### ISSUE TITLE
Kéne help! Van olyan parancs a botban hogy egy bizonyos csatornába írsz bármit automatikusan megkasz egy kiválasztott rangot?

### ISSUE THREAD

**Issue by Matyitm** [FightMan01/fightman01bot#201]
**Kérdés leírása**
Egy jól érthető leírás a kérdésedhez...

**Comment by GamerTomii** [comment]
Olyan parancs, ami bármikor odaad egy adott rangot, bármilyen üzenetre, tudtommal nincsen. De tudom ajánlani az ?!ellsetup-ot, ami küld egy DM üzenetet annak, aki belép a szerveredre, és ha beírja egy adott csatornába az ott kapott kódot, akkor odaadja a kiválasztott rangot.
