### ISSUE TITLE
?!weather hiba

### ISSUE THREAD

**Issue by petipeti156** [FightMan01/fightman01bot#209]
**Hiba leírása**
?!weather nem működik

**Bővebb részletek**
Nem tudja lekérni a városok időjárását, már tegnap (tudtommal) óta. (kép)
![Screenshot_20201208_154550](https://user-images.githubusercontent.com/61799060/101498901-e9669f00-396c-11eb-8dc7-0de54f022b74.jpg)

**Comment by FightMan01** [comment]
Javítva.
