### ISSUE TITLE
Téma hiba

### ISSUE THREAD

**Issue by GamerTomii** [FightMan01/fightman01bot#21]
**Hiba leírása**
Amikor csinálok egy új szobát, akkor log-ba azt írja hogy téma megváltoztatva.

**Bővebb részletek**
Azt írja régi témának, hogy "None", újnak meg azt hogy "Nincs"

**Minek kéne történnie?**
Semminek xd

**Képernyőfotók**
https://cdn.discordapp.com/attachments/666391839301042186/702407613345824828/unknown.png

UI.: Bocsi az előző jelentésért, balfasz voltam :"D

**Comment by FightMan01** [comment]
Köszi a jelentést!
