### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by InvisibleMan780** [FightMan01/fightman01bot#211]
Mi a színváltoztatás parancsa fightman szélén?

**Comment by FightMan01** [comment]
Nem értelek.

**Comment by InvisibleMan780** [comment]
![kép](https://user-images.githubusercontent.com/75687224/101508879-77945280-3978-11eb-88b5-cfa7da0341cd.png)
erre gondolok

**Comment by FightMan01** [comment]
Nincs olyan parancs.

**Comment by InvisibleMan780** [comment]
oké :(
