### ISSUE TITLE
Botparancs

### ISSUE THREAD

**Issue by InvisibleMan780** [FightMan01/fightman01bot#212]
![kép](https://user-images.githubusercontent.com/75687224/101509159-c3df9280-3978-11eb-8126-5dd2d60dd322.png)
szinváltoztatós parancs :) _?!setcolur szín

**Comment by GamerTomii** [comment]
Ebből a képből nem sokat tudunk kideríteni, mivel elég sok funkció van a botban amit be lehet kapcsolni. :+1:

**Comment by InvisibleMan780** [comment]
![kép](https://user-images.githubusercontent.com/75687224/101530983-eb435900-3992-11eb-8ac3-add72b0fb5b4.png)

**Comment by InvisibleMan780** [comment]
![kép](https://user-images.githubusercontent.com/75687224/101531092-10d06280-3993-11eb-976d-eee2a09f0258.png)

**Comment by GamerTomii** [comment]
És ezeken mit kéne nézni?

**Comment by davidfegyver** [comment]
hmm szerintem a színeket akarja változtatni 

mint pl a bannál kék helyett pirost akar.

?!setcolor ban red
?!setcolor ok darkgreen

**Comment by TancsicsGergely** [comment]
Nem is rossz ötlet
Adunk neki egy esélyt, lehet bekerül a karácsonyival :D

**Comment by InvisibleMan780** [comment]
Remélem 👍

**Comment by InvisibleMan780** [comment]
?!setclour leave cyan

**Comment by FightMan01** [comment]
Ilyen egy ideig biztos nem lesz. Minden parancs beírásakor le kéne kérni az adatbázisból, hogy milyen színt használjon, ami meg még pluszban terhelné. Ennyit szerintem nem ér meg.
