### ISSUE TITLE
Kréta rendszer értesítő hiba

### ISSUE THREAD

**Issue by davidfegyver** [FightMan01/fightman01bot#213]
# Sziasztok!! 👋
Tancsics irányított ide engem :D 
## Hiba leírása
Naszóval, az **előző 4 fightman bottól kapott házimból 2 nem az enyém**, mindkettőben volt google meet link ami szerintem elég veszélyes.
Mondtátok hogy töröljem az adataim. Megtettem, utána egy pici idővel újra előjött a hiba.

## Információk:
 - OS: Windows 10 Home
 - Discord app verzió: Stable 72915 (cac681d)

AD:
(Kövess be githubon vagy adj pár csillagot😉⭐)

**Comment by davidfegyver** [comment]
Ma is kaptam kettő nem nekem való házit :D

**Comment by TancsicsGergely** [comment]
Ez még mindig kréta api kiszolgáló hiba, egyenlőre semmit sem tudunk vele csinálni...
