### ISSUE TITLE
AutoRole Kikapcsolása 1 megadott rangra

### ISSUE THREAD

**Issue by kispintyi** [FightMan01/fightman01bot#219]
Sziasztok! Hogy tudom az autorole parancsnál az egyik rangot kivenni? Mert hiába kapcsolom ki a funkciót utána be és adok meg rangot, a másik rangot ugyanúgy megadja mellé, ami nem kellene nekem, bármi ötlet, hogy hogy oldjam ezt meg? :c megpróbáltam azt a trükköt is, hogy kikapcsoltam, bekapcsoltam, hozzáadtam azt a rangot ami nem kell és kikapcsoltam és bekapcsoltam, aztán megint megadtam azt a rangot ami kell, de ugyanúgy mellé rakta a másik rangot ami nem kell, remélem tudnak erre valami megoldást javasolni vagy ilyesmi.

Köszönöm!

**Comment by FightMan01** [comment]
Bugnak tűnik, megnézem.

**Comment by kispintyi** [comment]
Rendben! Köszönöm!

**Comment by FightMan01** [comment]
Esetleg egy szerver ID-t tudsz adni?

**Comment by kispintyi** [comment]
Igen! ID: 564129711509340162

**Comment by FightMan01** [comment]
Úgy látom, hogy a szerveren ki van kapcsolva az autorole, vagy rossz szerver ID-t adtál meg.

**Comment by kispintyi** [comment]
jót adtam meg

**Comment by kispintyi** [comment]
elvileg pedig be van kapcsolva

**Comment by FightMan01** [comment]
Be tudsz hívni a szerverre?

**Comment by kispintyi** [comment]
igen

**Comment by kispintyi** [comment]
egyébként írta a szabályzat elfogadást a szerver?
