### ISSUE TITLE
Ötlet

### ISSUE THREAD

**Issue by Fate9** [FightMan01/fightman01bot#22]
?!blockcmd add [parancs alapja] és ?!blockcmd remove [parancs alapja]
Parancs blokkolás.
Példa: ?!blockcmd add ?!say

Ehez a parancshoz van egy kis ötletem ami szerintem nagyon jó lenne a szerverekre, hogy egy bizonyos csatornában is tud tiltani a parancsokat.

**Comment by FightMan01** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/29693718/79975719-b59d3e80-849b-11ea-88a9-92b70c007974.png">

**Comment by Fate9** [comment]
Igen de én ügy értem hogy másol az a parancs mehetne. 
pl: ?say le van tiltva a #duma szobábn de a #parancsok szobában lehesen használni.

**Comment by FightMan01** [comment]
Áhh, értem.
