### ISSUE TITLE
Egy parancs, ami törli az *összes* csatornáról az *összes* üzenetet

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01/fightman01bot#221]
**Részletek**
Egy parancs (ha megvalósítható), ami törli az egész szerver *minden* üzenetét (pl. *?!clearall* vagy *?!clearserver*)

**Comment by GamerTomii** [comment]
Ez nem lehetséges, ugyanis egy bot nem tud 14 napnál régebbi üzeneteket törölni. + ennek eléggé nuke feelingje van.
