### ISSUE TITLE
Dashboard hibák

### ISSUE THREAD

**Issue by ZetenyiAron** [FightMan01/fightman01bot#224]
Elég furán néz ki telefonon a dashboard. Minek sorolja fel az összes szerveremet? miért nem csak azt ahol admin vagyok? Olyan lehetne hogy ha nincs behívva a bot akkor azt irja hogy bot behívása, ha bevan akkor azt hogy tovább a dashboardra.

**Comment by FightMan01** [comment]
1. Az áttekintésnél sorolja csak fel az összeset, a prefix választónál csak azokat, ahol van jogod (szerver tulajoknak alapból van, a többieknek a ?!webadmin paranccsal lehet adni)
2. Az értelmes ember csak tudja, hogy hova hívta be a botot.
