### ISSUE TITLE
Ellenőrző rendszer bug

### ISSUE THREAD

**Issue by sooresz** [FightMan01/fightman01bot#225]
Azt vettem észre, hogy a bot az ellenőrzés után (a verify után) nem veszi el és nem adja meg a rangokat.

**Comment by FightMan01** [comment]
Ez egyedi problémának hangzik. Kérlek ellenőrizd, hogy a bot rangja a legmagasabb-e, illetve, hogy a botnak van-e joga.

**Comment by sooresz** [comment]
ok. köszi
