### ISSUE TITLE
Nyereményjáték

### ISSUE THREAD

**Issue by XxkataxX** [FightMan01/fightman01bot#226]
Nem működik a nyereményjáték.A szilveszteri nyereményjátékba tegnaop nyertem,de a kód amit küldött nem működik.Ezt írja"Sajnos nem nyertél semmit".Ha szeretne képernyőfotót akkor kérem írjon rám discordon.(Nevem: Xx_kata_xX#7720,megtalál a FightMan01 bot hivatalos szerverén.)

-Discord app verzió:53.8

**Comment by FightMan01** [comment]
Ez nem így működik. Azokat a nyereményeket én osztom ki, de erre még nem került sor, de ma estig ez meg fog történni. 
Szíves türelmedet kérem.

**Comment by XxkataxX** [comment]
Köszönöm válaszát.Elnézést a zavarásért.

**Comment by TancsicsGergely** [comment]
(Amúgy nem kell önözni, nem vagyunk mi öregek 😂)

**Comment by XxkataxX** [comment]
Xddd
