### ISSUE TITLE
Hiba

### ISSUE THREAD

**Issue by Fate9** [FightMan01/fightman01bot#23]
![Screenshot_20200422-165241_Chrome](https://user-images.githubusercontent.com/62769758/79997840-4420b880-84ba-11ea-8d5f-14cf2daed9b8.jpg)
Nekem ezek nem működnek azt irja ki folyton hogy kérlek várj...

**Comment by Fate9** [comment]
Oh akkor nem is fog működni soha?

**Comment by FightMan01** [comment]
A soha azért erős kifejezés ide :)
