### ISSUE TITLE
Ellsetup BUG

### ISSUE THREAD

**Issue by zarandthebende** [FightMan01/fightman01bot#233]
**Hiba leírása**
*Meg akarom hívni a saját botomat kikapcsolt verification rendszernél, de a bot nem enegedi*

**Bővebb részletek**
*Ha meghívom a saját botomat a szerverre, a welcome rendszer kiírja, hogy csatlakozott, majd a leave rendszer pedig kiírja, hogy kilépett, de a bot nem küld üzenetet privátba (Pl. "Az ellenőrzés sikertelen, mert a felhaszhnáló nem fogad üzeneteket")*

**Minek kéne történnie?**
*A botomnak belépnie a szerverre*

**Információk:**
* - Discord app verzió (ha azt használod) [pl.: Canary 57889 (492e1b6)]*

**Comment by TancsicsGergely** [comment]
Kapcsold ki a verification rendszert amíg meghívod a botodat.

**Comment by zarandthebende** [comment]
Már megvolt

**Comment by TancsicsGergely** [comment]
A discord dev portálon a botod publikusra van állítva?

**Comment by zarandthebende** [comment]
Nem, miért?

**Comment by zarandthebende** [comment]
Ebből gondolom hogy annak kéne lennie

**Comment by zarandthebende** [comment]
Ha public akkor is ezt csinálja...

**Comment by FightMan01** [comment]
Nem értem ennek mi köze az ellenőrző rendszerhez. Itt más a gond.

**Comment by zarandthebende** [comment]
Csak annyi szerintem hogy ameddig be volt kapcsolva az ellenőrző rendszer addig küldött a bot egy privátot, hogy nem fogad a felhaszmáló üzenete, és ezért nem tud belépni...kikapcsoltam, és ugyanez van, csak üzenet nélkül. De ha te mondod...

**Comment by Elydra5** [comment]
Uhm attól még hogy “a felhasználó nem fogad üzenetet” szöveget megkapod nem kell arra következtetni, hogy a bot kickeli ki. Én is sokszor megkaptam ezt az üzenetet, mégse kickelte ki az fm01 bot az illetőt. Ugyan úgy ott volt a kis elzárt szobában, rajta a nem engedélyezett role. Ha azt levettem róluk és rájuk adtam egy verifyedet akkor máris bent voltak a szerveren

**Comment by TancsicsGergely** [comment]
Amúgy igen, nézd meg az audit log-ot a szerver beállításokban, hogy ki/mi kickeli

**Comment by Elydra5** [comment]
Smurt

**Comment by zarandthebende** [comment]
A bot kitiltja, legalábbis a log ezt irja

**Comment by FightMan01** [comment]
És milyen indokkal?

**Comment by Elydra5** [comment]
Pics now

**Comment by FightMan01** [comment]
Mert szerintem neked a raid mód aktív.

**Comment by Elydra5** [comment]
Figyelj Áron a végén be lesz kapcsolva neki a raid mod xdddd

**Comment by zarandthebende** [comment]
Elydra5 Es tenyleg XDD...ekkora barom legyek

**Comment by Elydra5** [comment]
L
　　M
　　　 A
　　　　 O
　　　　　o
　　　　　 o
　　　　　o
　　　　 。
　　　 。
　　　.
　　　.
　　　 .
　　　　.

**Comment by zarandthebende** [comment]
Köszi :DD
