### ISSUE TITLE
?!twicehost névjavítás

### ISSUE THREAD

**Issue by FMate01** [FightMan01/fightman01bot#235]
Sziasztok. Mivel már nem Twicehostnak hívják a rádiót, hanem FreshFM-nek, a **?!twicehost** parancsot is **?!fresmfm** névre át kellene nevezni szerintem.

Köszönöm.

**Comment by shadowcoftheworld** [comment]
Bruh

**Comment by FightMan01** [comment]
Át van nevezve egy ideje, csak a régivel is lehet használni, hátha valaki azt ismeri.
