### ISSUE TITLE
Helyesírási hiba

### ISSUE THREAD

**Issue by 2005zsombor2005** [FightMan01/fightman01bot#24]
**Hiba leírása**
Ha a ?!kréta parancsot használom akkor van egy helyesírási hiba a botban.

**Bővebb részletek**
Amikor használom a ?!kréta parancsot akkor jön privátban egy olyan üzenet, hogy "Üdv! Kérlek a kezdéshez írdd meg a botnak, hogy 'Indítás'"

**Minek kéne történnie?**
Nem "írdd", hanem "írd".

**Képernyőfotók**
[https://cdn.discordapp.com/attachments/703229279953223791/703285396192362604/Hiba_Fm01.png](url)

**Információk:**
 - By: 2005zsombor2005#0061

**Comment by FightMan01** [comment]
Köszi, majd javítjuk.
