### ISSUE TITLE
Autoping

### ISSUE THREAD

**Issue by shadowcoftheworld** [FightMan01/fightman01bot#241]
Jó estét uraim, gondoltam bevezethetnék azt a csodás elképzelést, hogy ha valaki a segítségkérőbe ír, és nem rendelkezik "segítő" ranggal, akkor a bot pingelje meg azt. Ugyanis látom sokak tudatáig nem jutott el az a mondat, hogy "Ha segítségre lenne szükséged, nyugodtan említsd meg a @『💁』Segítő rangot."

**Comment by GamerTomii** [comment]
What an idea

**Comment by ZetenyiAron** [comment]
Ez azt jelentené hogy ha valaki válaszol, aki nem segítő akkor minden üzenetnél pingelne a bot, szerintem a segítők hamar agybajt kapnának xd. Aki segítséget kér elolvsshatja hogy mit lehet pingelni. Szerintem.

**Comment by shadowcoftheworld** [comment]
Idáig 1 ember pingelt. Természetesen lenne a botban egy olyan funkció, mely válaszadáskor eltárolja, hogy arra válaszoltak, és csak a következő segítségkérésnél pingelne
