### ISSUE TITLE
Weboldalon hiba

### ISSUE THREAD

**Issue by 2005zsombor2005** [FightMan01/fightman01bot#25]
**Hiba leírása**
A weboldalon a fun parancsok menüben a weather parancs kétszer van.

**Minek kéne történnie?**
Nem kellene kettő

**Képernyőfotók**
https://cdn.discordapp.com/attachments/703229272743084033/703654179041968188/Nevtelen.png

**Információk:**
 - by: 2005zsombor2005#0061

**Comment by FightMan01** [comment]
Köszi, hamarosan javítva lesz!

**Comment by FightMan01** [comment]
Javítva!
