### ISSUE TITLE
Emlékeztető rendszer

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#28]
- Fix / állandó emlékeztetés 
 
Akár napi/heti/havi  emlékeztetés

Itt arra gondolok hogy _minden vasárnap 12:00 küld  egy szöveges üzenetet: privatba (itt  nem egyénire gondolok hanem max 50 főig) / cchannelbe

Emlékeztetés  x idő után "elévüljön" magyarul törlödjön
_

Képes legyen az  @everyone-ra

- ?!listreactionlog ->Listázza a reaction logot 

- Log-ból channeleket ki lehessen kapcsolni 

Válaszokat várom

**Comment by TancsicsGergely** [comment]
Köszönjük az ötleteket, megnézzük, hogy mit tehetünk ez ügyben.

**Comment by Roli0109** [comment]
@FightMan01

**Comment by FightMan01** [comment]
Ez már tervben van.

**Comment by FightMan01** [comment]
Később kerül megvalósításra...
