### ISSUE TITLE
Reactrole

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#3]
1: a reactrole lehetne nem _?!rangsetup_, hanem **?!reactrole**
2: elfogadhatná a saját emotikonokat is
3: **";"** jellel elválasztva lehetne több rang is
4: **";"** jellel elválasztva lehetne több emotikon is _(csak ha több rang van)_
5: lehetne beállítani saját üzenetre reactrole-t _(mint Carl-botnál)_
6: adjá jogot reakcióra he (#infók)
#teamFightMan01

**Comment by FightMan01** [comment]
1. Okés, rakok rá aliast.
2. Elfogadja már egy ideje :D 
3-4. Tervben van multi is.
5. Sztem mind1, hogy a bot küldi, vagy te.
6. Már rég megvolt.

**Comment by FightMan01** [comment]
#5
