### ISSUE TITLE
Bot által kiírt üzenet

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#30]
?!csay  és társai képesek legyenek képet is küldeni

----------

Legyen jelentés ha a bot moderál 
Pl warn list

**Comment by PrestiaCountryballs** [comment]
Csay? Miért nem csaj a neve? Kicsit figyel oda.

**Comment by TancsicsGergely** [comment]
?!csay -> *c*hannel*say*
Amúgy @Roli0109 van warnlist parancs

**Comment by Roli0109** [comment]
@TancsicsGergely 
Warnlistnál nem jelenik meg a bot álltal figyelmeztetett ember 

Pl amikor trágár szavakat ir, stb

**Comment by FightMan01** [comment]
De megjelenik már.

**Comment by FightMan01** [comment]
A csay oké.
