### ISSUE TITLE
ChatCare Bug

### ISSUE THREAD

**Issue by KDominik12** [FightMan01/fightman01bot#32]
**Hiba leírása**
Az lenne a hiba hogy mikor a ChatCaret használom nem törli ki az üzenetet ami a csúnya szó

**Minek kéne történnie?**
Hogy kitörölje az üzenetet

**Képernyőfotók**
https://media.discordapp.net/attachments/701769462956818482/707219636495712267/unknown.png?width=841&height=475

**Információk:**
 - OS: Windows
 - Discord legújabb verzió pontosan nem találom

**Comment by FightMan01** [comment]
Nincs joga, vagy a discord bugol.
A discord bugnál csak a küldőnél nem lesz törölve, mindenki másnál igen.
