### ISSUE TITLE
Log lekérdezés

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#34]
Hamár a log számolja hogy x ember hány reakciót rakott nem lehetne lekérdezni hogy: 
Bizonyos szemely milyen reakciot rakott és mennyit vagy 
Bizonyos reakciót hany szemely hanyszor hasznalta

**Comment by FightMan01** [comment]
`Bizonyos reakciót hany szemely hanyszor hasznalta` -> Ezt nem tudom, hogyan oldjam meg szépen. Mármint azt, hogy elkérjem azt tudom, csak hogyan írjam ki.

**Comment by Roli0109** [comment]
Könyv mintázat ? 
Amit multkor küldtem neked ?

**Comment by Roli0109** [comment]
Esetleg táblázat? 
Vagy esetleg felsorolásként?

**Comment by FightMan01** [comment]
> Könyv mintázat ?
Hát lehet, hogy úgy lesz, de arra magamban ki kell találnom valami módszert :D
Ez lehet el fog egy ideig tartani.

**Comment by Roli0109** [comment]
> > Könyv mintázat ?
> Hát lehet, hogy úgy lesz, de arra magamban ki kell találnom valami módszert :D
> Ez lehet el fog egy ideig tartani.

 
Akkor maradjunk az egyszerű táblázatnál 


Küldök ma egy mintát

**Comment by FightMan01** [comment]
Oks.

**Comment by Fate9** [comment]
Olyat kéne hogy bizonyos parancsot tudnál tiltani egy szobbában pl.: van a teszt szoba ado tudnál használni minden parancsot de a teszt2 -ben nem tudnál használni olyan parancsot amit tiltunk a szobában.

**Comment by FightMan01** [comment]
> Olyat kéne hogy bizonyos parancsot tudnál tiltani egy szobbában pl.: van a teszt szoba ado tudnál használni minden parancsot de a teszt2 -ben nem tudnál használni olyan parancsot amit tiltunk a szobában.

Külön issue-ba kérlek.

**Comment by FightMan01** [comment]
Done.
