### ISSUE TITLE
Parancs tiltó szóbákra

### ISSUE THREAD

**Issue by Fate9** [FightMan01/fightman01bot#35]
Olyat kéne hogy bizonyos parancsot tudnál tiltani egy szobbában pl.: van a teszt szoba ado tudnál használni minden parancsot de a teszt2 -ben nem tudnál használni olyan parancsot amit tiltunk a szobában.

**Comment by FightMan01** [comment]
Ez szerintem felesleges, a sima parancs blokkoló ott van.
