### ISSUE TITLE
Horoszkop

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#37]
Napi 
Havi 
Heti

**Comment by FightMan01** [comment]
👌

**Comment by FightMan01** [comment]
Kicsit kifejtenéd, hogy mégis mit, és hogyan gondolsz?
Mert ez nekem ilyenformában új :D

**Comment by Roli0109** [comment]
@FightMan01 
 ?dailybak Lekérdezi a napi horoszkópot 
?!weeklybak  Lekérdezi a het horoszkopt
