### ISSUE TITLE
Információ

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#40]
?!informing @emlités <Tájékoztató szöveg>
?!informlist
?!setinflevel hány db után  mute/kick/ban/warn

**Comment by FightMan01** [comment]
A `?!setinflevel hány db után mute/kick/ban/warn` már létezik `?!setmodlevel` néven.

**Comment by FightMan01** [comment]
A többi meg jegyzet rendszerként üzemel (?!set_note, ?!notes, ?!delete_note)

**Comment by Roli0109** [comment]
Itt nem magamnak akartam, hanem mast informálni és nyoma legyen a logban

**Comment by FightMan01** [comment]
Aha, de oda meg akár a `?!dmsay` is szóba jöhet.

**Comment by Roli0109** [comment]
De azt nem tudom lekövetni ?!dmlist parancs nincs sajnos
