### ISSUE TITLE
Mute

### ISSUE THREAD

**Issue by program2k20** [FightMan01/fightman01bot#42]
**Hiba leírása**
Mikor muteolva van valaki majd lelép a szerverről és vissza akkor lekerül róla a rang.

**Bővebb részletek**
Lemuteolsz valakit majd az a személy kilép majd vissza és már nincs rajta az a rang
**Minek kéne történnie?**
Rajta kéne, hogy maradjon a rang

**Képernyőfotók**
Lásd tegnap arnus.

**Információk:**
 - OS: Windows 10 Pro
 - Böngésző (ha arról használod a discordot) Applikációban és böngészőben jelen van
 - Discord app verzió (ha azt használod) Stable 60073 (1a5d710)

**Comment by FightMan01** [comment]
😑

**Comment by FightMan01** [comment]
Tekinthető hibának is, de igazából nincs is megcsinálva, hogy rajta maradjon.

**Comment by program2k20** [comment]
Akkor ez mehet öteltekbe is :D

**Comment by FightMan01** [comment]
Inkább az kéne :D
