### ISSUE TITLE
A bot belépked a szobába

### ISSUE THREAD

**Issue by LeviiiTheReal** [FightMan01/fightman01bot#46]
**Hiba leírása**
A bot folyamatosan belépked a szobába ahol vagyunk, utána meg kilép. Ezt ismételgeti.

**Bővebb részletek**
Semmilyen olyan parancsot nem írunk be, amitől be kellene lépnie a szobába. Csak work, crime, ilyesmi. A mai nap folyamán lekértük a pinget egyszer 33557 ms volt, ez nem tudom mennyire számít mivel nem ma jelentkezett először a probléma. (Most is megnéztem gyorsan 496 ms volt)

**Minek kéne történnie?**
Nem kellene belépnie magától.

**Képernyőfotók**
Nem tudok képet csatolni, a be-ki lépés szobákból logolása ki van kapcsolva. Arról, hogy a bot egyszer bent van a szobában egyszer nincs gondolom nem kell kép.

**Információk:**
 - OS: Windows 10 64-bit
 - Böngésző: -
 - Discord app verzió: Stable 60259 (e36411b)

**Comment by FightMan01** [comment]
A discord európai voice szerveri többször is összeomlottak...
Ez a probléma mindenkit érint, akik akkor használták a botot.
A hiba javítása hamarosan megtörténik.

**Comment by FightMan01** [comment]
A ping kb semmit sem számít, az egy message roundtrip.
