### ISSUE TITLE
Weboldal Parancs lista

### ISSUE THREAD

**Issue by Zolkaa** [FightMan01/fightman01bot#48]
![Screenshot_20200518-114303](https://user-images.githubusercontent.com/62213354/82199297-cce61500-98fd-11ea-99f0-328bad424c60.png)
**Hiba leírása**
Egy rövid, de jól megfogalmazott leírás a hibáról.

**Bővebb részletek**
Lépések, hogy hogyan tudjuk a hibát előidézni.

**Minek kéne történnie?**
Ide írd, hogy szerinted minek kéne történnie.

**Képernyőfotók**
Ha lehet, képet csatolj!

**Információk:**
 - OS: [pl.: MacOS 10.15.4]
 - Böngésző (ha arról használod a discordot) [pl.: safari]
 - Discord app verzió (ha azt használod) [pl.: Canary 57889 (492e1b6)]

**Comment by FightMan01** [comment]
Érvénytelen hibajelentés, nem írtál részletet. Ezek nem véletlenül vannak itt, kérlek nyiss egy újat, és töltsd ki ezeket is.
<img width="529" alt="image" src="https://user-images.githubusercontent.com/29693718/82203502-b2af3580-9903-11ea-8185-88f78a20be00.png">
