### ISSUE TITLE
Nsfw csatorna

### ISSUE THREAD

**Issue by Meszi84** [FightMan01/fightman01bot#49]
**Kérlek írd le az ötlet részleteit.**
Egy bő, jól érthető leírás az ötletedhez!
Sok lány kérdezte/kérik nsfw csatornán miért nincs pasi.

**Comment by Roli0109** [comment]
@Meszi84 
Tudod a nők nem pornónak🤣🤣

**Comment by FightMan01** [comment]
Érdekes ötlet, ezt egy API szolgáltatja. De csinálok olyan parancsot, amely fiúkat is ad :D

**Comment by Meszi84** [comment]
Hát... tőllem mindig kérdezik "pasi miért nincs a botban?" 😀

**Comment by PrestiaCountryballs** [comment]
🤦 nem tudom

**Comment by FightMan01** [comment]
Esetleg, ha valaki erre tud végpontot, akkor szívesen fogadom :)

**Comment by TancsicsGergely** [comment]
Mivel nem tudtunk ilyen végpontot találni/nem adott senki, ezt az issuet lezárom.
