### ISSUE TITLE
[RFC] Gyorsaság növelés.

### ISSUE THREAD

**Issue by FightMan01** [FightMan01/fightman01bot#50]
Ebben az újabb projektben ismételten nagyobb változások fognak történni.
Most a gyorsaságról és stabilitásról fog szólni:

- [x] `json` modul helyett `aiofiles` használata.
- [x] ~~Az `rds` rendszer újragondolása, `urllib` helyett `aiohttp` használata.~~ - Header gondok :(

## `aiofiles vs json`
![](https://miro.medium.com/max/1400/1*KUd1TZ7-8efpQ_7XLKSKmw.png)

**Comment by FightMan01** [comment]
RFC = Request For Comment

**Comment by PrestiaCountryballs** [comment]
oké

**Comment by FightMan01** [comment]
Megjegyzés: Az `rds`-t sikerült megoldani, már az is `aiohttp` modul segítségével megy :)
