### ISSUE TITLE
Template készítő

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#52]
Egy template készítő parancs, mely segítségével templateket lehet készíteni.
Elképzelés: ?!template <list, create, delete> <név> Szerintem nem is kell részleteznem melyik argumentum mit tud. Ha beírod a ?!template create exmaple, akkor készítsen egy exmaple nevű template-t, melyet ha betöltesz, a te szerveredet tölti be.

**Comment by FightMan01** [comment]
Ez kb olyan mint a ?!mentes parancs. 
Amíg nem tudom tökéletesíteni azt, addig ilyen nem várható.
