### ISSUE TITLE
setmodlevel kicsi update

### ISSUE THREAD

**Issue by Fate9** [FightMan01/fightman01bot#54]
?!setmodlevel [mute/kick/ban] [mennyi warn után]

Szerintem ehez a parancshoz jó lenne még a tempmute és a tempban is.

**Comment by FightMan01** [comment]
Tempban bizonyos okok miatt egyelőre nem lesz, tempmute talán, de nem hiszem, hogy mostanság lenne megvalósítva, elég nagy projektek futnak most.
