### ISSUE TITLE
?!template1 igen nem működik

### ISSUE THREAD

**Issue by TancsicsGergely** [FightMan01/fightman01bot#56]
**Hiba leírása**
A ?!template1 igen nem csinál semmit (?!template1 válaszol) A többi template működött (logban nem volt semmi hiba ránéztem)

**Bővebb részletek**
há írd be vazze xd

**Minek kéne történnie?**
Szerver template-nek be kéne töltődnie

**Képernyőfotók**
![kép](https://user-images.githubusercontent.com/43749897/82835431-42388380-9ec4-11ea-83c0-43f74ed32a04.png)

**Információk:**
 - OS: Windows 10 os de ez mindegy xd
 - Discord app verzió titok :D

**Comment by TancsicsGergely** [comment]
javíccsad meg me megverlek megfele (jah és honap gyere WoT kekw)

**Comment by FightMan01** [comment]
Hmmmm, most megnéztem, és jó volt 🤔
