### ISSUE TITLE
Nem müködnek

### ISSUE THREAD

**Issue by Fate9** [FightMan01/fightman01bot#57]
?!pornhub (Mindenre azt irja, hogy nincs találat)
?!fortnitesneak (Nem történik semmi)
?!randomnév (Kérlek várj...)
?!pokemon (Nem történik semmi)
Valutákban semelyik nem megy

**Comment by FightMan01** [comment]
?!randomnév: halott api
?!fortnitesneak: halott api
Erről a kettőről régóta tudunk.
A ?!pornhub bugos, de sajnos nincs másik api.

Valuták működnek, pokemon is.
<img width="485" alt="image" src="https://user-images.githubusercontent.com/29693718/82899882-f89b7780-9f5b-11ea-8684-97a9b1cb9400.png">
