### ISSUE TITLE
Rang a neved ellöt

### ISSUE THREAD

**Issue by Fate9** [FightMan01/fightman01bot#58]
Lehetne egy olyan parancs, hogy ?!tag és azt csinálná lényegben hogy amilyen rangú az illető pl: Tag, VIP, Troll, stb. annak a neve élé ki írná a rangot ha a funkciót be kapcsolod. Mert sok szerveren láttam ezt és mindenki kézzel írja elé.

**Comment by FightMan01** [comment]
Ezt már sokan említették, de ha több rangot kap, akkor a neve egy össze-visszaság lenne.

**Comment by Fate9** [comment]
Úgy gondoltam hogy csaj a legnagyobb rangját irná ki vagy azt nem lehetséges megcsinálni?

**Comment by FightMan01** [comment]
Normális módon nehezen kivitelezhető, mert könnyen össze lehet zavarni, és könnyen lehet bugoltatni :(
