### ISSUE TITLE
?!afk parancs kiegészítés

### ISSUE THREAD

**Issue by TancsicsGergely** [FightMan01/fightman01bot#59]
**Kérlek írd le az ötlet részleteit.**
Egy bő, jól érthető leírás az ötletedhez!

![kép](https://user-images.githubusercontent.com/43749897/82996142-d4e03c00-a004-11ea-8a12-e6a10748cb9e.png)

**Comment by FightMan01** [comment]
Jó ötlet :P

**Comment by FightMan01** [comment]
2 ezres frissítésben benne lesz ;)
