### ISSUE TITLE
log

### ISSUE THREAD

**Issue by GamerTomii** [FightMan01/fightman01bot#62]
**Hiba leírása**
A log 3x írja ki a rang elvételeket

**Bővebb részletek**
Pl. amikor lejárt a haveromnak a Boost-ja, akkor 3x írta ki, hogy elvette a Booster rangot.

**Minek kéne történnie?**
1x kéne kiírnia. kekw

**Képernyőfotók**
https://cdn.discordapp.com/attachments/666391839301042186/715208142119632978/unknown.png
https://cdn.discordapp.com/attachments/666391839301042186/715208872574320730/unknown.png

**Információk:**
 - OS: windóz 10
 - Discord app verzió: Stable 60661 (578c2e8)

**Comment by FightMan01** [comment]
Regarding to #61 .
