### ISSUE TITLE
Channel 

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#64]
Ezzel a paranccsal be lehetne állítani hogy minden üzenet alá reakciót rakjon a bot.

?!reakcióch #channel max 2 reakció

**Comment by FightMan01** [comment]
🤔

**Comment by FightMan01** [comment]
Kétezres frissítésben várható lesz ;)
<img width="380" alt="image" src="https://user-images.githubusercontent.com/29693718/83357753-9208c600-a36e-11ea-8f57-c3d229ed5f4b.png">
