### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#66]
Invitemanager funkció. Ki / be lehessen kapcsolni, számolná a meghívásokat, hogy ki hívta meg stb, lennének role-reward-ok, és lehetne embedben is köszönteni az embereket.

**Comment by FightMan01** [comment]
Az embedes jó ötlet, a többit már próbáltam, de nehéz lenne rate limit nélkül megoldani ilyen szerverszám mellett. (Az invitemanager is sokszor kap rate limitet, ezért offline gyakran)

**Comment by FightMan01** [comment]
Embedes köszöntés a 2 ezer szerveres frissítésben bent lesz ;)
