### ISSUE TITLE
Időzítés

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#68]
Valahogy meg kellene oldani hogy például sajat beállítás 
6-18ig minden üzenetről jöjjön értesités 
18-22ig csak az említésről jöjjön értesites
22-06ig semmirol ne jojjon 

Egyénileg be tudjuk állitani a bottal

**Comment by FightMan01** [comment]
Botok egyelőre ezt nem tudják megcsinálni :(
