### ISSUE TITLE
kilépés

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#69]
1 parancs-> amikor kilép valaki akkor automatikusan törli az összes üzenetét.

Megoldható ?

**Comment by FightMan01** [comment]
Ennek lehetnek korlátozásai API oldalon, mivel nemrég új rate limit szabályokat vezettek be.
Majd megnézem, hogy lehetséges-e.

**Comment by FightMan01** [comment]
Sok üzenet esetén guild rate limitet kap, ezért nem tudom belerakni. (Illetve bele tudom, ha bevállalja a szerver tulaja, hogy kb 10 percig nem lehet a botot használni a szerveren, miután olyan lépett ki, akinek sok üzenete volt)

**Comment by Roli0109** [comment]
Én bevállalom

**Comment by FightMan01** [comment]
Még azért megnézem a további dolgokat, mert global rate limitet nem akarok.
