### ISSUE TITLE
Removerole

### ISSUE THREAD

**Issue by Meszi84** [FightMan01/fightman01bot#73]
**Hiba leírása**
Egy rövid, de jól megfogalmazott leírás a hibáról.

Moderátor, rendessen konfigolva nem tudja elvenni a rangot. Rége sikerült elvenni a rangot.

Elvegye a rangot

**Képernyőfotók**

**Információk:**
 Android pie
Ver 23.0
![Screenshot_20200604-231121_Discord](https://user-images.githubusercontent.com/60156956/83810885-28175600-a6b9-11ea-8d18-2a88392dba47.jpg)

**Comment by FightMan01** [comment]
Elírta a parancsot! 
Helyes írva: **?!removerole**
