### ISSUE TITLE
Új template

### ISSUE THREAD

**Issue by vrolandd** [FightMan01/fightman01bot#74]
Szerintem lehetne egy template, ami kifejezetten a digitális oktatásra szánt, ha megint digitális oktatás lenne. Pl. Tanári közlemények, ilyesmik. Persze ezt is akkor, ha újra digitális oktatás lesz.

**Comment by FightMan01** [comment]
Szerintem már nem lesz, de egyébként ezt már az elején megcsináltuk:
https://discord.new/ZkvTzKKPnQPV
