### ISSUE TITLE
Level system rework

### ISSUE THREAD

**Issue by klmnblzs** [FightMan01/fightman01bot#75]
Na csá.
Egy level system rework szerintem jól jönne. Szintlépéskor economy cuccok stbstbstb, nem tudom mennyire lenne rá igény

**Comment by 182marci** [comment]
Be lehessen állítani a level system-nél, hogy mondjuk 6. szintnél kapjon az illető egy rangot.

**Comment by FightMan01** [comment]
> Be lehessen állítani a level system-nél, hogy mondjuk 6. szintnél kapjon az illető egy rangot.

Ilyen a kezdete óta van: **?!levelrole**

**Comment by 182marci** [comment]
Uhh bocsi

**Comment by FightMan01** [comment]
Mivel az economy global, ezért nincs benne ilyen.

**Comment by 182marci** [comment]
És mi lenne, ha a prémium pontok lennének globálisak, és az economy nem?

**Comment by FightMan01** [comment]
Most már ezt átalakítani szinte lehetetlen. Ezt így szokták már meg az emberek.

**Comment by 182marci** [comment]
![image](https://user-images.githubusercontent.com/51509676/83940666-2c8d5d00-a7e6-11ea-8d8f-359840a8e2bf.png)
