### ISSUE TITLE
Új profilkép a botnak

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#78]
Csináltam egy új profilképet a botnak, de próbáltam törekedni arra, hogy annyira azért ne térjen el a mostanitól. Tetszik?

![favicon](https://user-images.githubusercontent.com/51509676/84166543-55775180-aa75-11ea-8c0c-5343f2a26aab.png)

**Comment by FightMan01** [comment]
Jól néz ki, de egyelőre cserét nem tervezünk 😅
De azért lementettem arra az esetre 😉
