### ISSUE TITLE
Bevétel szerzés

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#79]
Helyezzétek a Google Adsense-t a weboldalatokon (Google hirdetések) így biztos bevételre tettek szert.

**Comment by FightMan01** [comment]
Tudunk a létezéséről, de jelenleg nem tervezzük a bevezetését. A sok bevétel gondot okozhat, ezért fontos kordában tartani a dolgot.

**Comment by TancsicsGergely** [comment]
Hirdetések a weboldalon biztosan nem lesznek, mert teljesen elrontanák azt. Ráadásul a bot egy nonprofil projekt, amit nem a bevétel miatt indítottunk. Az a pénz amit a támogatóktól kapunk pont elég a vps kifizetésére, ennyi nekünk elég.

**Comment by Greenoliv** [comment]
Esetleg, ha be lesz vezetve a webhost, akkor prémium pontot lehet venni igazi pénzért is.
