### ISSUE TITLE
Roli ötletei

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#8]
?!multiwarn {Szöveg} {@említések,vel evalasztva}

?!fixreminder #channel /Hét melyik napján hány órakor/  {Emlékeztető szöveg}

?!delfixreminder

?!visszaszámláló ( mikor legyen vége pl 2020.02.02 12:05) #channel (üzenet )

Statisztika (Jakab jancsi x reakciót rakott a cy channelbe( tevékenység logolás)

?!sör 

?!bor

?!pálinka

?!kokó

 Atlagárak

**Visszajelzést szeretnék kérni **__

**Comment by FightMan01** [comment]
A multiwarn az azért felejtős, mert a sok DM üzenetet tiltja a discord.
A fixreminder oké.
A delfixreminder szintén.
A visszaszámlálót kifejtenéd egy kicsit jobban?
A statisztikát megpróbálom.
Átlagárakra tudsz adni oldalt?
