### ISSUE TITLE
Webhost részleg

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#81]
Nesze itt a host részleg terve. Becsüld mert sokat dolgoztam vele :'D

![Fightman01 host](https://user-images.githubusercontent.com/51509676/84177101-b35e6600-aa82-11ea-85f4-54568fb9648a.png)

**Comment by TancsicsGergely** [comment]
kisz név kekw
kommunista ifjak szövetsége :kappa:

**Comment by 182marci** [comment]
?????????????

**Comment by 182marci** [comment]
Mit töröté?

**Comment by TancsicsGergely** [comment]
Nem rossz, de még sok mindent meg kell csinálni azelőtt, h tényleg legyen ilyen

**Comment by 182marci** [comment]
"Repository owner deleted a comment from 182marci now" de nem töröltél semmit

**Comment by 182marci** [comment]
Lol megint

**Comment by FightMan01** [comment]
Egyébként erre lehet, hogy külön vps lesz!

**Comment by 182marci** [comment]
Lol te akkor is tudsz ide írni, mikor le van zárva? 🤔

**Comment by FightMan01** [comment]
A repo tulaja vagyok, még újranyitni is tudom ;)

**Comment by FightMan01** [comment]
De le tudom így zárni.
