### ISSUE TITLE
Játékismertető bot funkció

### ISSUE THREAD

**Issue by Elydra5** [FightMan01/fightman01bot#82]
Dr. Gerdzson úrnak leírtam már privátban, hogy olyan csodás ötletem lenne, miszerint a botban létezne egy olyan funkció, hogy beírok egy játéknevet, (for example ?!warthunder) ééés akkor a bot kiírná, hogy mi a játék lényege, milyen gépigénye van stb stb stb, szóval egy ilyen rövidke kis ismertetőt tenne ki róla. Néhány "gamer" szerveren hasznos lenne i think, ahol felmerülnek olyan no name játékok mint pl az escape from tarkov vagy hasonlók, és valaki nem tudná, hogy mi az adott játék, miről szól stb

**Comment by TancsicsGergely** [comment]
igen az úr tényleg jelezte a csodás ötletét majd megcsinálom őket holnap
annyit kérek h gyűjtsél pár olyan játékot amit így első körben megcsinálok

**Comment by Elydra5** [comment]
hát ömm én itt arra gondoltam, hogy csináltok egy ilyen kereső bigyót, hogy beírsz valamit és google keresés alapján különféle szűrőrendszerekkel megtűzdelve dobná ki a magyarázatot. pl hogy csak wikipédia lapot dobjon fel mint ismertető, és a gépigény oldalt pedig a gépigény résznél

**Comment by TancsicsGergely** [comment]
köszönöm drága uram majd megcsinálom 👍

**Comment by Elydra5** [comment]
köszönöm az úr gyors válaszát

**Comment by FightMan01** [comment]
Kérlek írd meg nekem a játék részleteket, mert Gergely erről nekem nem is mondott semmit :D

**Comment by TancsicsGergely** [comment]
xd majd én megcsinálom
nem olyan nehéz egy embed xd

**Comment by FightMan01** [comment]
Na azt megnézem, ha te megcsinálod.....

**Comment by TancsicsGergely** [comment]
:ugyvanparasztigazadvan:

**Comment by 182marci** [comment]
Mi folyik itt? lmao

**Comment by 182marci** [comment]
<:ugyvanparasztigazadvan:709303638421405797>

**Comment by TancsicsGergely** [comment]
ah yes

**Comment by TancsicsGergely** [comment]
![kép](https://user-images.githubusercontent.com/43749897/85869659-4958f700-b7cc-11ea-93ba-658f642d2ac5.png)
*spoiler*

**Comment by 182marci** [comment]
ezmiazanyám

**Comment by 182marci** [comment]
Mr. pixel image
