### ISSUE TITLE
spamszűrő

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#83]
**Hiba leírása**
olvasd el a dct

**Bővebb részletek**
sokat spammelek és más is ír és neki jelez be. én bypassolva vagyok.

**Minek kéne történnie?**
gergelynek be kéne vallania hogy búzy

**Képernyőfotók**
https://media.discordapp.net/attachments/572111556075192343/720914654066507786/gay.png?width=102&height=102
**Információk:**
 - OS: windówz 10 64-Bit (10.0.17763)
 - Böngésző (ha arról használod a discordot): nothin
 - Discord app verzió (ha azt használod): Stable 61473 (76b907a)

**Comment by FightMan01** [comment]
Másnak nem jelezhet be, és kérlek ne trollkodj a hibajelentéssel, ez ilyen formában amúgy is érvénytelen!

**Comment by iamdoms** [comment]
öh, de másnak is bejelzett, kérdezd meg shadowcrackert, bejelzett azért mert én szavanként írtam
