### ISSUE TITLE
Chatcare: Antispam feature

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#86]
**Hiba leírása**
Akkor is figyelmeztet spam miatt, ha csak simán gyorsan írok.

**Bővebb részletek**
Írj gyorsan lmao

**Minek kéne történnie?**
Nem kéne figyelmeztetnie a botnak <:ugyvanparasztigazadvan:709303638421405797>

**Képernyőfotók**
Szerintem ezt már nem is kell csatolnom...

**Információk:**
- Tök mindegy, mert ez nem a gépedtől függ.

**Comment by FightMan01** [comment]
A szerver tulajdonosa szabadon konfigurálhatja, finomíthat, hogy hogyan jelezzen.
Részletek a parancsok oldalon.
