### ISSUE TITLE
Economy rendszer

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#87]
Több fajta “szituációt” hozzáadni a slut, crime, work, luck parancshoz, mert már egy idő után elég unalmas mindig ugyanazt a szöveget olvasni. (Pl a work parancshoz: felkértek, hogy tervezz meg egy weboldalt, és ezzel 2000 Ft-t kerestél)

**Comment by TancsicsGergely** [comment]
Már csináltunk egyszer egy felmérést, hogy ki milyen szöveget tenne bele, azok bele is kerültek, majd lehet megint lesz ilyen, vagy szerver alapú parancs még nem tudjuk
