### ISSUE TITLE
Még több ötlet

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#9]
Bot logolja: - hang csatorna be/ki lépést átalakítása --> ( @Roli0109  Belépett a hangcsatornába) 

"Az előző csatorna ,mostani csatorna  nem nagyon tetszik "

Reakció hozzáadásnál irja ki azt h hányadszor adta hozzá a héten azt a jelet 

?!pokemon <pokemon név> -> kiadja a pokemon nevét adatait es hogy lehet e shiny

?!ingress <cella  kód>  ->  kiadja a cella állását

?!zár/nyit  -> @everyone tiltás/engedélyezés

**Comment by FightMan01** [comment]
A hangcsatornásat már átalakítottam, a kövi frissítésben biztos bent lesz olyan formában :)
`Reakció hozzáadásnál irja ki azt h hányadszor adta hozzá a héten azt a jelet` - Ezt az előző ötleteidhez leírtam, megpróbálom.
A pokemont is megpróbálom, meg az ingress-t is.
A zár/nyit parancsot nem teljesen értem, ezt kifejtenéd mégjobban?

**Comment by Roli0109** [comment]
Zár/nyit: letiltja/ feloldja az adott csatornában az everyoneozást
