### ISSUE TITLE
Nem reagál.

### ISSUE THREAD

**Issue by NimdAstic** [FightMan01/fightman01bot#91]
**Hiba leírása**
Nem reagál a bot.
**Bővebb részletek**
A rangokat hozzáadtam a bothoz, de amiután meg akartam változtatni a prefixét, nem reagált. Újra is hívtam a botot, de nem ment.

**Minek kéne történnie?**
Reagálnia kéne. :D

**Képernyőfotók**
Nem tudok.

**Információk:**
 - OS: [pl.: Android 9.0]
 - Discord app verzió: Nemtom... xD

**Comment by TancsicsGergely** [comment]
Valószínűleg sikerült megváltoztatni a prefixet
Itt meg tudod nézni, hogy mire cserélted le: https://fightman01bot.hu/dashboard
