### ISSUE TITLE
Ötlet: kiadni az új dashboard-ot

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#92]
kiadni az új dashboard-ot

**Comment by TancsicsGergely** [comment]
:pepereeeeee:

**Comment by 182marci** [comment]
:face_with_raised_eyebrow:

**Comment by 182marci** [comment]
De tényleg, mikor lesz kiadva?

**Comment by TancsicsGergely** [comment]
Remélem nemsokára, már nincs iskola -> tudok vele foglalkozni

**Comment by 182marci** [comment]
<:ugyvanparasztigazadvan:716394813213114368>
