### ISSUE TITLE
?!időszavazás parancs nem működik

### ISSUE THREAD

**Issue by 182marci** [FightMan01/fightman01bot#93]
**Hiba leírása**
Miután beírod az időszavazás parancsot, úgy ahogy a bot kéri, kitörli a bot a parancsot, de nem válaszol

**Bővebb részletek**
Írd be az ?!időszavazás parancsot

**Minek kéne történnie?**
Működnie

**Képernyőfotók**
nope

**Információk:**
- Nem szükséges

**Comment by FightMan01** [comment]
Az issue template azért van, hogy kitöltsd. Olyan, hogy “nem szükséges” nem fogadható el, ennek értelmében ez akár érvénytelen is lehetne. 
Egyébként megnéztem, és működött. (1 perces idővel)
