### ISSUE TITLE
Szerver Lista

### ISSUE THREAD

**Issue by Prestia01** [FightMan01/fightman01bot#95]
Ez egy Olyan Ötlet, Ami Lenne Olyan Parancs Hogy ?!ServerList @Prestia Countryballs#0002
És Kiirja hogy Milyen Szerverbe van bent

**Comment by Prestia01** [comment]
Valaki ír már kommentem egy tulajdonos? Megpingelem a tulajdonosokat @FightMan01 @TancsicsGergely

**Comment by 182marci** [comment]
Ennek fuss neki mégegyszer

**Comment by FightMan01** [comment]
Látjuk akkor is, ha nem írunk, egyébként ilyen biztos nem lesz.
