### ISSUE TITLE
Log rendszer

### ISSUE THREAD

**Issue by Roli0109** [FightMan01/fightman01bot#96]
Logoslást szét tudjuk szedni channelekbe!

Pl ?!logwarn #logwarn

**Comment by Roli0109** [comment]
+ ötlet

vmit ne loggoljon a bot
?!addignorechannellog [csatorna]

**Comment by FightMan01** [comment]
A szétszedés nem valószínű, mert az már megint egy újraírást igényelne, de az ignore az megvalósítható.
