### ISSUE TITLE
szegény hibaüzenet

### ISSUE THREAD

**Issue by iamdoms** [FightMan01/fightman01bot#98]
**Hiba leírása**
rossz a hibaüzenet

**Bővebb részletek**
?!ban vagy ?!kick

**Minek kéne történnie?**
._.

**Képernyőfotók**
https://media.discordapp.net/attachments/636975333576409118/724260458785144972/unknown.png?width=263&height=260

**Információk:**
 - OS: Windows 10 Pro 1909 (Windows 10 64-Bit)
 - Böngésző: nem azt használom, de amúgy Google Chrome (ha csak onnan tudom)
 - Discord app verzió: Stable 58164

**Comment by FightMan01** [comment]
Valamiert nem talalja. Ilyet akkor ir, ha a user lista nulla.
